# Generated by Django 3.0.5 on 2021-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('meta_keywords', models.TextField()),
                ('meta_current_page_url', models.CharField(max_length=511)),
                ('meta_description', models.CharField(max_length=165)),
                ('meta_image_url', models.URLField()),
                ('file_location', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('facebook_sharing_link', models.CharField(max_length=1023)),
            ],
        ),
    ]
