# Generated by Django 3.0.5 on 2021-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=80)),
                ('url_title', models.CharField(max_length=80)),
                ('featured_image', models.ImageField(blank=True, upload_to='article_pictures')),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_current_page_url', models.CharField(blank=True, max_length=511, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=165)),
                ('meta_image_url', models.CharField(blank=True, max_length=200)),
                ('images', models.TextField(blank=True, null=True)),
                ('facebook_sharing_link', models.CharField(blank=True, max_length=1023)),
                ('publish_status', models.BooleanField(default=False)),
                ('categories', models.CharField(blank=True, max_length=511)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=63)),
            ],
        ),
    ]
