# Generated by Django 3.0.5 on 2021-01-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_title',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
