# Generated by Django 3.1.7 on 2021-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_location',
            field=models.CharField(default='templates/articles/', max_length=255),
        ),
    ]
