# Generated by Django 3.0.5 on 2021-03-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='article_link',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='user_id',
        ),
    ]
