# Generated by Django 3.0.5 on 2021-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('category_name', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
        ),
    ]
