# Generated by Django 3.0.5 on 2021-03-29 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20210328_0544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('article_id', 'user_id')},
        ),
    ]
