# Generated by Django 3.1.7 on 2021-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210331_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_title',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
