# Generated by Django 3.0.5 on 2021-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='browser_details',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='os_details',
        ),
        migrations.AddField(
            model_name='viewer',
            name='browser_family',
            field=models.CharField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewer',
            name='browser_version',
            field=models.CharField(default=2, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewer',
            name='os_family',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewer',
            name='os_version',
            field=models.CharField(default='a', max_length=42),
            preserve_default=False,
        ),
    ]
