# Generated by Django 3.0.5 on 2021-02-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
