# Generated by Django 3.0.5 on 2021-03-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210331_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='browser_version',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='os_version',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
