# Generated by Django 3.0.5 on 2021-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_current_page_url',
        ),
    ]
