# Generated by Django 3.0.5 on 2021-03-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20210329_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('device_agent', models.CharField(choices=[('M', 'Mobile'), ('T', 'Tablet'), ('P', 'PC')], max_length=1)),
                ('is_touch_capable', models.BooleanField(default=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('browser_details', models.CharField(max_length=255)),
                ('os_details', models.CharField(max_length=255)),
                ('device_agent_family', models.CharField(max_length=73)),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('article_id', 'user_id', 'ip_address')},
            },
        ),
    ]
