# Generated by Django 3.1.7 on 2021-04-02 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20210331_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
