# Generated by Django 3.0.5 on 2021-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_facebook_sharing_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
