# Generated by Django 3.0.5 on 2021-01-14 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_User_Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.ImageField(upload_to='profile_pictures')),
                ('locale', models.CharField(default='en', max_length=10)),
            ],
        ),
    ]
