# Generated by Django 3.0.5 on 2021-03-29 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_user_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_interaction',
            name='engagement_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
