# Generated by Django 3.0.5 on 2021-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_user_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_detail',
            name='image_url',
            field=models.CharField(max_length=80),
        ),
    ]
