# Generated by Django 3.0.5 on 2021-03-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extra_user_detail', '0002_auto_20210329_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_interaction',
            name='date_last_read',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article_interaction',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
