# Generated by Django 3.0.5 on 2021-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_user_detail', '0002_auto_20210121_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_user_detail',
            name='verified_profile',
            field=models.BooleanField(default=False),
        ),
    ]
