# Generated by Django 3.0.5 on 2021-03-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_user_detail', '0004_auto_20210327_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_Interaction',
        ),
    ]
